Repository pivotal/LicenseFinder, pull requests merged in 2020-01, with the labels that each got.

#650 Replace whitelist/blacklist terminology
  README.md
  features/features/cli/cli_spec.rb
  features/features/configure/approve_dependencies_spec.rb
  features/features/configure/blacklist_licenses_spec.rb
  features/features/configure/permitted_licenses_spec.rb
  features/features/configure/restricted_licenses_spec.rb
  features/features/report/html_spec.rb
  lib/license_finder/cli.rb
  lib/license_finder/cli/blacklist.rb
  lib/license_finder/cli/main.rb
  lib/license_finder/cli/permitted_licenses.rb
  lib/license_finder/cli/restricted_licenses.rb
  lib/license_finder/cli/whitelist.rb
  lib/license_finder/core.rb
  lib/license_finder/decision_applier.rb
  lib/license_finder/decisions.rb
  lib/license_finder/license_aggregator.rb
  lib/license_finder/package.rb
  lib/license_finder/packages/merged_package.rb
  lib/license_finder/reports/templates/html_report.erb
  lib/license_finder/reports/templates/markdown_report.erb
  license_finder.gemspec
  spec/lib/license_finder/cli/main_spec.rb
  spec/lib/license_finder/cli/permitted_licenses_spec.rb
  spec/lib/license_finder/cli/restricted_licenses_spec.rb
  spec/lib/license_finder/decision_applier_spec.rb
  spec/lib/license_finder/decisions_spec.rb
  spec/lib/license_finder/license_aggregator_spec.rb
  spec/lib/license_finder/package_spec.rb
  spec/lib/license_finder/reports/csv_report_spec.rb
  spec/lib/license_finder/reports/html_report_spec.rb
  spec/lib/license_finder/reports/json_report_spec.rb
Labels: scheduled

#651 [FEATURE] Ensure composer always installs the packages
  lib/license_finder/package_managers/composer.rb
  spec/lib/license_finder/package_managers/composer_spec.rb
Labels: unscheduled

#658 Change version to be required for `dependency add` and updated cli options
  features/features/configure/add_dependencies_spec.rb
  features/features/configure/restricted_licenses_spec.rb
  features/features/report/html_spec.rb
  lib/license_finder/cli/approvals.rb
  lib/license_finder/cli/dependencies.rb
  lib/license_finder/cli/makes_decisions.rb
  spec/lib/license_finder/cli/dependencies_spec.rb
Labels: scheduled

#660 Add ruby 2.7.0 and update to latest patch levels
  Dockerfile
  Rakefile
Labels: in progress

#659 Add support for Pipfile.lock
  features/features/package_managers/pipenv_spec.rb
  features/support/testing_dsl.rb
  lib/license_finder/package_manager.rb
  lib/license_finder/package_managers/pip.rb
  lib/license_finder/package_managers/pipenv.rb
  lib/license_finder/package_utils/pypi.rb
  lib/license_finder/scanner.rb
  spec/fixtures/all_pms/Pipfile.lock
  spec/fixtures/pipenv-with-lockfile/Pipfile
  spec/fixtures/pipenv-with-lockfile/Pipfile.lock
  spec/lib/license_finder/package_managers/pipenv_spec.rb
  spec/lib/license_finder/package_utils/pypi_spec.rb
Labels: scheduled

#663 Fix crash when handling certain python dependencies conditions
  bin/license_finder_pip.py
  features/features/package_managers/pip_spec.rb
  features/support/testing_dsl.rb
  lib/license_finder/package_managers/pip.rb
  spec/lib/license_finder/cli/main_spec.rb
  spec/lib/license_finder/package_managers/pip_spec.rb
Labels: in progress

#664 [Fixed] Testing dsl now correctly creates gem project
  features/features/report/diff_spec.rb
  features/support/testing_dsl.rb
Labels: unscheduled
