Repository pivotal/LicenseFinder, pull requests merged in 2021-01, with the labels that each got.

#805 Feature: "check-require-only" for Composer
  lib/license_finder/cli/base.rb
  lib/license_finder/cli/main.rb
  lib/license_finder/configuration.rb
  lib/license_finder/core.rb
  lib/license_finder/package_managers/composer.rb
  spec/fixtures/config/composer_license_require_only.json
  spec/lib/license_finder/core_spec.rb
  spec/lib/license_finder/package_managers/composer_spec.rb
Labels: in progress

#806 Upgrade pip3 to 20.0.2.
  Dockerfile
Labels: scheduled

#813 Updated node version to 14.x
  Dockerfile
Labels: unscheduled
